In [89]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [ ]:
input = None
with open("input2.txt", 'r') as f:
    input = [int(i) for i in f.read()]
input

[2, 3, 3, 3, 1, 3, 3, 1, 2, 1, 4, 1, 4, 1, 3, 1, 4, 0, 2]

In [ ]:
is_free = False
file_index, index_tracker = 0, 0
array = np.array([-1] * sum(input))
for n in input:
    if is_free:
        index_tracker += n
        is_free = False
    else:
        array[index_tracker:index_tracker+n] = file_index
        index_tracker += n
        file_index += 1
        is_free = True
array

array([ 0,  0, -1, -1, -1,  1,  1,  1, -1, -1, -1,  2, -1, -1, -1,  3,  3,
        3, -1,  4,  4, -1,  5,  5,  5,  5, -1,  6,  6,  6,  6, -1,  7,  7,
        7, -1,  8,  8,  8,  8,  9,  9])

In [95]:
mut_array = array.copy()

free_spaces = np.where(array == -1)[0]
files_to_move = np.flip(np.where(array[free_spaces.min():] != -1)[0] + free_spaces.min())[:len(free_spaces)]
# files_to_move
print(array[files_to_move])
# print(free_spaces)

[9 9 8 8 8 8 7 7 7 6 6 6 6 5]


In [96]:
mut_array[free_spaces] = array[files_to_move]
mut_array[len(array) - len(free_spaces):] = -1
mut_array

array([ 0,  0,  9,  9,  8,  1,  1,  1,  8,  8,  8,  2,  7,  7,  7,  3,  3,
        3,  6,  4,  4,  6,  5,  5,  5,  5,  6,  6, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1])

In [97]:
num_files = len(array) - len(free_spaces)
print(mut_array[num_files-1], mut_array[num_files])

6 -1


In [98]:
checksum = np.sum(mut_array[:num_files] * np.arange(num_files))
checksum

np.int64(1928)

In [ ]:
checksum = np.sum(mut_array[:num_files] * np.arange(num_files))
checksum

np.int64(1928)